version: "3"

services:
  db:
    image: postgres:10.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    # restart: always

  web:
    container_name: budget_tool
    env_file: .env
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    # restart: always

volumes:
  postgres_data:
